title: GaussRun
description: Small notes from building things.
author: GaussRun
url: https://gaussrun.github.io
baseurl: /micro-blog
theme: minima
permalink: /:year/:month/:day/:title.html
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
github_username: GaussRun
